[tool.poetry]
name = "pycvrplib"
version = "0.1.0"
description = "Python library for working with CVRPLIB files."
authors = ["Leon Lan <leon.lanyidong@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
numpy = ">=1.15"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
flake8-unused-arguments = "^0.0.10"
black = "^22.3.0"
isort = "^5.10.1"
pytest = "^7.1.2"
mypy = "^0.950"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
